version: "3.8"

services:
    mongodb:
        image: mongo
        restart: always
        ports:
            - ${MONGO_PORT:-27017}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}

    # **Optional** (comment/remove if mongo-express is not needed)
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - ${MONGO_EXPRESS_PORT:-8081}:8081
        depends_on:
            - mongodb
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-root}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-password}
            ME_CONFIG_MONGODB_SERVER: mongodb
            # ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
